### ISSUE TITLE
Pre-publication checklist

### ISSUE THREAD

**Issue by jvita** [jvita/abbrv#12]
This is a list of tasks that should be completed before publishing the webpage:

- [x] finish re-implementing Orthic, cleaning/adding features along the way
- [x] change the drafter to only load the files once, then to store them in a variable which can be edited on-the-fly without having to re-load.
- [x] move all spline drawing logic to the client side
- [ ] make a first draft of one of the more popular systems (Pitman, Gregg, Forkner, etc.)
- [x] add the ability to import/export the system (upload/download `glyphs.json`, `modes.json`, `phrases.json`, and `rules.json`, probably as a zip file)
- [ ] ask Kyle and Nathan to beta test
